version: '2'
services:
    saafa-app:
        image: saafa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://saafa-mysql:3306/saafa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    saafa-mysql:
        extends:
            file: mysql.yml
            service: saafa-mysql
